// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myApiTreeView.API.Data;

namespace myApiTreeView.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180819063408_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("myApiTreeView.Models.Folder", b =>
                {
                    b.Property<int>("FolderId");

                    b.Property<string>("Name");

                    b.Property<int?>("ParentFolderId");

                    b.HasKey("FolderId");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("folders");
                });

            modelBuilder.Entity("myApiTreeView.Models.TestCase", b =>
                {
                    b.Property<int>("TestCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<int?>("FolderId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("StepCount");

                    b.HasKey("TestCaseId");

                    b.HasIndex("FolderId");

                    b.ToTable("testCases");
                });

            modelBuilder.Entity("myApiTreeView.Models.Folder", b =>
                {
                    b.HasOne("myApiTreeView.Models.Folder", "ParentFolder")
                        .WithMany("SubFolders")
                        .HasForeignKey("ParentFolderId");
                });

            modelBuilder.Entity("myApiTreeView.Models.TestCase", b =>
                {
                    b.HasOne("myApiTreeView.Models.Folder", "folder")
                        .WithMany("TestCases")
                        .HasForeignKey("FolderId");
                });
#pragma warning restore 612, 618
        }
    }
}
